### PR TITLE
Send notification mail when node comes back online after being offline

### PR DESCRIPTION
**Pull request by ghost**
This patch also sends a notification mail when an offline node comes back online. This ensures users are informed when the issue has been resolved.

### CODE REVIEW

**Comment by Philhil** [comment]
Thank you very much for your contribution

**Comment by Philhil** [comment]
We Have to improve this. Now the system is sending emails when a Node get back online even if no alarm.
The algorithm is like this:

1. Node of a task is offline -> mark task->offlinesince with current datetime
2. If the node is offlinesince (time) + intervall (timespan) lower than now than 3.
3. Send Alert Mail if $task->lastalert == null || $task->lastrun != $task->lastalert) 

The back online notoification should only be send if a alarm Mail was driggert. In code: 
`if ($task->lastalert != null && $task->lastrun == $task->lastalert) {
//send back online notification
}`

**Comment by ghost** [comment]
Okay, I’ll fix this on GPN and update this PR.

**Comment by ghost** [comment]
Oh, now you’ve fixed it yourself. Sorry it took me so long to fix this. Nevertheless, you can find my fixes with some refactoring in #6.

**Pull request merged**
